spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/content_plan
    username: postgres
    password: admin12345
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show-sql: true
        database: content_plan
        default_schema: content_plan
        id:
          db_structure_naming_strategy: single
    hibernate:
      use-new-id-generator-mappings: false
      hbm2ddl:
        auto: validate
      ddl-auto: validate

server:
  port: 8088
logging:
  level:
    content.plan: debug
