spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/content_plan
    username: postgres
    password: admin12345
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show-sql: true
        database: content_plan
        default_schema: content_plan
    hibernate:
      ddl-auto: validate
      id:
        sequence:
          increment_size_mismatch_strategy: LOG

server:
  port: 8088
logging:
  level:
    root: INFO
    content_plan: DEBUG
    org:
      springframework:
        security: DEBUG
  file:
    name: app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

